spring:
  application:
    name: store-core
  jackson:
    property-naming-strategy: SNAKE_CASE
    threads:
      virtual:
        enabled: true
    
  datasource:
    url: jdbc:postgresql://store-core-db:5432/storecoredb
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://store-core-db:5432/storecoredb
    user: postgres
    password: 1

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      acks: all
      enable.idempotence: true
      max.in.flight.requests.per.connection: 5
    consumer:
      group-id: store-core-group
      auto-offset-reset: earliest

  elasticsearch:
    uris: elasticsearch:9200

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 51730

management:
  server:
    port: 51731
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
      # 100% of requests are traced. must lower to 0.1-0.5 in server for optimization
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://alloy:4318/v1/traces
  otlp:
    metrics:
      export:
        enabled: false

logging:
  level:
    root: INFO
    org:
      apache:
        kafka: WARN

app:
  cleanup:
    cron: 0 0 0 * * ?
    timezone: CET
  activation-ttl-minutes: 15
  inactive-account-ttl-days: 1
  kafka:
    replicas: 3
    min-insync-replicas: 2

jwt:
  starter:
    enabled: true
    issuer: "axgiri@proton.me"
    jwks-uri: "http://store-auth:51720/api/v1/.well-known/jwks.json"

minio:
  url: http://minio:9000
  access-key: 123456789qwerty123456789qwerty123456789qwerty
  secret-key: 123456789qwerty123456789qwerty123456789qwerty
  bucket:
    default: default-bucket
    persons: persons-bucket
    products: products-bucket

kafka:
  topic:
    report: report-topic
    review: review-topic
    registration: registration-topic
    registration-compensate: registration-compensate-topic


api:
  service:
    notification-reports: http://notification-service:51740/api/notifications
    store-authentication:
      base-url: http://store-auth:51720/api/v1/users
      validate: /is-email-available

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 80
        record-exceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
          - tech.github.storecore.exception.ServiceCommunicationException
    instances:
      store-auth:
        base-config: default
        sliding-window-size: 5
        wait-duration-in-open-state: 10s

max:
  photo:
    per:
      product: 5