services:
  store-core-k6:
    image: eclipse-temurin:25-jdk-alpine
    container_name: store-core-k6
    hostname: store-core
    ports:
      - "52730:51730"
    volumes:
      - ../../:/app
    environment:
      GITHUB_PACKAGES_USER: ${GITHUB_PACKAGES_USER:?set GITHUB_PACKAGES_USER in .env}
      GITHUB_PACKAGES_TOKEN: ${GITHUB_PACKAGES_TOKEN:?set GITHUB_PACKAGES_TOKEN in .env}
      SPRING_PROFILES_ACTIVE: k6
    working_dir: /app
    command: ./mvnw -s /app/.mvn/settings-docker.xml spring-boot:run -Dspring-boot.run.jvmArguments="--enable-preview"
    depends_on:
      store-core-db-k6:
        condition: service_started
      elasticsearch-k6:
        condition: service_healthy
      minio-k6:
        condition: service_started
    networks:
      - store-core-k6-network
      - store-network
    restart: on-failure:3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  store-core-db-k6:
    image: postgres:18-alpine
    container_name: store-core-db-k6
    ports:
      - "51731:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: storecoredb
    volumes:
      - store_core_db_data:/var/lib/postgresql/data
    networks:
      - store-core-k6-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d storecoredb -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure:3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  elasticsearch-k6:
    image: elasticsearch:9.2.4
    container_name: elasticsearch-k6
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.collection.enabled=false
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - store-core-k6-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure:3
    deploy:
      resources:
        limits:
          memory: 512m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  minio-k6:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: minio-k6
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "123456789qwerty123456789qwerty123456789qwerty"
      MINIO_ROOT_PASSWORD: "123456789qwerty123456789qwerty123456789qwerty"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web console
    volumes:
      - minio_data:/data
    networks:
      - store-core-k6-network
    restart: on-failure:3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
    store-core-k6-network:
        driver: bridge
    store-network:
      external: true
        

volumes:
  store_core_db_data:
  es_data:
  minio_data: